options:
  corosync_bindnetaddr:
    type: string
    description: |
      Network address of the interface on which corosync will communicate
      with the other nodes of the cluster.
  corosync_mcastaddr:
    default: 226.94.1.1
    type: string
    description: |
      Multicast IP address to use for exchanging messages over the network.
      If multiple clusters are on the same bindnetaddr network, this value
      can be changed.
  corosync_mcastport:
    default: 5405
    type: int
    description: |
      Multicast Port number to use for exchanging messages. If multiple
      clusters sit on the same Multicast IP Address, this value needs to
      be changed.
  corosync_pcmk_ver:
    default: 1
    type: int
    description: |
      Service version for the Pacemaker service version. This will tell
      Corosync how to start pacemaker
  corosync_key:
    type: string
    description: |
      This value will become the Corosync authentication key. To generate
      a suitable value use:
      .
        corosync-keygen
      .
      This configuration element is mandatory and the service will fail on
      install if it is not provided.
