options:
  corosync_mcastaddr:
    default: 226.94.1.1
    type: string
    description: |
      Multicast IP address to use for exchanging messages over the network.
      If multiple clusters are on the same bindnetaddr network, this value
      can be changed.
  corosync_pcmk_ver:
    default: 0
    type: int
    description: |
      Service version for the Pacemaker service version. This will tell
      Corosync how to start pacemaker
  corosync_key:
    type: string
    default: corosync-key
    description: |
      This value will become the Corosync authentication key. To generate
      a suitable value use:
      .
        corosync-keygen
      .
      This configuration element is mandatory and the service will fail on
      install if it is not provided.
  stonith_enabled:
    type: string
    default: 'False'
    description: |
     Enable resource fencing (aka STONITH) for every node in the cluster.
     This requires MAAS credentials be provided and each node's power
     parameters are properly configured in its invenvory.
  maas_url:
    type: string
    description: MAAS API endpoint.
  maas_credentials:
    type: string
    description: MAAS credentials.
