options:
  corosync_mcastaddr:
    default: 226.94.1.1
    type: string
    description: |
      Multicast IP address to use for exchanging messages over the network.
      If multiple clusters are on the same bindnetaddr network, this value
      can be changed.
  corosync_pcmk_ver:
    default: 1
    type: int
    description: |
      Service version for the Pacemaker service version. This will tell
      Corosync how to start pacemaker
  corosync_key:
    type: string
    default: "64RxJNcCkwo8EJYBsaacitUvbQp5AW4YolJi5/2urYZYp2jfLxY+3IUCOaAUJHPle4Yqfy+WBXO0I/6ASSAjj9jaiHVNaxmVhhjcmyBqy2vtPf+m+0VxVjUXlkTyYsODwobeDdO3SIkbIABGfjLTu29yqPTsfbvSYr6skRb9ne0="
    description: |
      This value will become the Corosync authentication key. To generate
      a suitable value use:
      .
        sudo corosync-keygen
        sudo cat /etc/corosync/authkey | base64 -w 0
      .
      This configuration element is mandatory and the service will fail on
      install if it is not provided.  The value must be base64 encoded.
  stonith_enabled:
    type: string
    default: 'False'
    description: |
     Enable resource fencing (aka STONITH) for every node in the cluster.
     This requires MAAS credentials be provided and each node's power
     parameters are properly configured in its invenvory.
  maas_url:
    type: string
    description: MAAS API endpoint (required for STONITH).
  maas_credentials:
    type: string
    description: MAAS credentials (required for STONITH).
  cluster_count:
    type: int
    default: 2
    description: Number of peer units required to bootstrap cluster services.
